openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string
  /projects:
    get:
      operationId: getProjects
      summary: Get list of all projects
      description: Get list of all projects
      tags:
        - Projects
      responses:
        '200':
          description: Get list of all projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/project"
        "default":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      operationId: createProject
      summary: Post a new project
      description: Add new project
      tags:
        - Projects
      requestBody:
        description: New project
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project'
      responses:
        '201':
          description: created new project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /projects/{projectId}:
    get:
      operationId: findProject
      summary: Find a project by id
      description: Find a project by id
      tags:
        - Projects
      parameters:
        - name: projectId
          in: path
          required: true
          description: projectId
          schema:
            type: string
      responses:
        "200":
          description: Found project.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    put:
      operationId: updateProject
      summary: Update an existing project
      description: Update project
      tags:
        - Projects
      parameters:
        - name: projectId
          in: path
          required: true
          description: projectId
          schema:
            type: string
      requestBody:
        description: Update project
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project'
      responses:
        "200":
          description: Updated project information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      operationId: deleteProject
      description: Delete project
      summary: Deletes a project based on id
      tags:
        - Projects
      parameters:
        - name: projectId
          in: path
          required: true
          description: projectId
          schema:
            type: string
      responses:
        "204":
          description: Project deleted.
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /users:
    get:
      operationId: getUsers
      description: Gets all users
      summary: Gets all users
      tags:
        - Users
      responses:
        '200':
          description: Get list of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    post:
      operationId: createUser
      summary: Create a new user
      description: Add new user
      tags:
        - Users
      requestBody:
        description: New user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: created new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /users/{userid}:
    get:
      operationId: findUser
      summary: Find a user by id
      description: Find a user by id
      tags:
        - Users
      parameters:
        - name: userid
          in: path
          required: true
          description: userId
          schema:
            type: string
      responses:
        "200":
          description: Found user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      operationId: updateUser
      summary: Update an existing user
      description: Update user
      tags:
        - Users
      parameters:
        - name: userid
          in: path
          required: true
          description: userid
          schema:
            type: string
      requestBody:
        description: Updated user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "200":
          description: Updated user information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      operationId: deleteUser
      description: Delete user
      summary: Deletes a user based on id
      tags:
        - Users
      parameters:
        - name: userid
          in: path
          required: true
          description: userid
          schema:
            type: string
      responses:
        "204":
          description: User deleted.
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /invoices:
    get:
      operationId: getInvoices
      description: Get all invoices
      summary: Get all invoices
      tags:
        - Invoices
      responses:
        '200':
          description: All invoices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/invoice"
    post:
      operationId: createInvoice
      description: Create a new invoice
      summary: Create a new invoice
      tags:
        - Invoices
      requestBody:
        description: A new invoice
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invoice"
      responses:
        '201':
          description: created new invoice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoice'
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /invoices/{invoiceId}:
    get:
      operationId: findInvoice
      description: Find an invoice with id
      summary: Find an invoice with id
      tags:
        - Invoices
      responses:
        '200':
          description: Found invoice.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invoice"
        "default":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    user:
      description: A user in the system
      properties:
        id:
          type: string
          description: Id for user in the database
        firstName:
          type: string
          description: user's first name
        lastName:
          type: string
          description: user's last name
        isActive:
          type: boolean
          description: Indicates whether the user is on vacation / employed
    project:
      description: Schema for project
      properties:
        id:
          type: string
          description: Project's id
        title:
          type: string
          description: Project's title
        customer:
          type: string
          description: Customer who the project is for
        dateAdded:
          type: string
          description: Date when project was added
        status:
          type: string
          description: Project status
        members:
          type: array
          items:
            $ref: "#/components/schemas/user"
        manager:
          $ref: "#/components/schemas/user"
    invoice:
      description: Schema for invoice
      properties:
        id:
          type: string
          description: Id of the invoice
        title:
          type: string
          description: Title of the invoice
        sum:
          type: number
          description: Sum to be paid
        userFirstName:
          type: string
          description: First name of the user who submitted the invoice
        dateAdded:
          type: string
          description: Date when invoice was submitted
        status:
          type: string
          description: Status of the invoice
        bankAccount:
          type: string
          description: Bank account where the sum is paid